# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: make validate

      - name: install packages
        run: make install

      - name: action lint
        run: make lint

      - name: action test
        run: make test

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v2.2.4

        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
